version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-backend-cockpit
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: cockpit
      MYSQL_PASSWORD: cockpit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cockpit
